#' Generate individual plots from countsimQC_report output
#'
#' From the collection of ggplot objects that can be saved when generating a
#' countsimQC report, generate individual plots.
#'
#' @param ggplots_rds The path to a .rds file generated by
#'   \code{countsimQC_report} by setting \code{save_ggplots = TRUE}.
#' @param device One of "eps", "ps", "tex" (pictex), "pdf", "jpeg", "tiff",
#'   "png", "bmp", "svg" or "wmf" (windows only) (will be provided to the
#'   \code{ggsave} function from the \code{ggplot2} package).
#' @param output_dir The output directory where the plots will be generated.
#' @param n_datasets The number of data sets that are compared in the figures.
#'   Needed to set the size of the plots correctly.
#'
#' @author Charlotte Soneson
#'
#' @export
#'
#' @importFrom grDevices n2mfrow
#'
#' @return No value is returned, but plots are generated in the designated
#'   output directory.
#'
generate_individual_plots <- function(ggplots_rds, device = "png",
                                      output_dir = "./", n_datasets = 2) {
  col_row <- grDevices::n2mfrow(n_datasets)
  for (pl in names(ggplots_rds)) {
    if (any(sapply(c("bcv_edgeR", "dispersion_DESeq2", "_sephist", "_sepscatter"),
                   function(x) length(grep(x, pl)) > 0))) {
      ggsave(plot = ggplots_rds[[pl]], filename = paste0(pl, ".", device),
             path = output_dir, width = 4.5 * col_row[1],
             height = 4.5 * col_row[2], units = "in")
    } else {
      ggsave(plot = ggplots_rds[[pl]], filename = paste0(pl, ".", device),
             path = output_dir, width = 7, height = 5, units = "in")
    }
  }
}
